language: csharp
sudo: false
dist: trusty
mono: none
dotnet: 2.1.500
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1   
os:
  - linux
script:
  - dotnet restore
  - dotnet build -c Release
